pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://storage.googleapis.com/download.tensorflow.org/maven") }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // Google AI Edge SDK (Gemini Nano / AICore)
        maven { url = uri("https://storage.googleapis.com/download.tensorflow.org/maven") }
        maven { url = uri("https://jitpack.io") }
    }
}

rootProject.name = "AIControl"
include ':app'
